# Generated by Django 3.0.6 on 2020-07-14 18:50

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import taberna.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('preco_f', models.DecimalField(decimal_places=2, default=30.0, max_digits=8, verbose_name='Preço Família')),
                ('preco_g', models.DecimalField(decimal_places=2, default=25.0, max_digits=8, verbose_name='Preço Grande')),
                ('preco_m', models.DecimalField(decimal_places=2, default=20.0, max_digits=8, verbose_name='Preço Média')),
                ('preco_p', models.DecimalField(decimal_places=2, default=15.0, max_digits=8, verbose_name='Preço Pequena')),
            ],
            options={
                'verbose_name': 'Preço Pizza',
                'verbose_name_plural': 'Preços Pizzas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('produto', models.CharField(max_length=50, verbose_name='Produto')),
                ('estoque', models.BooleanField(verbose_name='Estoque')),
                ('imagem', stdimage.models.StdImageField(upload_to=taberna.models.get_filename, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taberna.Produto')),
            ],
            options={
                'verbose_name': 'Pizza',
                'verbose_name_plural': 'Pizzas',
            },
            bases=('taberna.produto',),
        ),
    ]
