# Generated by Django 3.0.6 on 2020-05-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='tamanho',
        ),
    ]
