# Generated by Django 3.0.6 on 2020-11-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('user', models.CharField(max_length=255, verbose_name='User')),
                ('product', models.CharField(max_length=255, verbose_name='Produto')),
                ('product_id', models.PositiveIntegerField(verbose_name='Produto ID')),
                ('product_type', models.CharField(max_length=25, verbose_name='Tipo')),
                ('details', models.CharField(max_length=25, verbose_name='Detalhes')),
                ('measure', models.CharField(max_length=25, verbose_name='Medida')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('amount', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('image', models.CharField(max_length=2000, verbose_name='Imagem')),
                ('date', models.CharField(max_length=20, verbose_name='Data')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taberna.Produto')),
                ('category', models.CharField(choices=[('beer', 'Cerveja'), ('whisky', 'Whisky'), ('vodka', 'Vodka'), ('energetic', 'Energético'), ('cognac', 'Conhaque'), ('cachaça', 'Cachaça'), ('rum', 'Rum'), ('soda', 'Refrigerante'), ('wine', 'Vinho'), ('varied', 'Variados')], max_length=10, verbose_name='Categoria')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Litros/Ml')),
            ],
            options={
                'verbose_name': 'Bebida',
                'verbose_name_plural': 'Bebidas',
            },
            bases=('taberna.produto',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taberna.Produto')),
                ('flavor', models.CharField(max_length=100, verbose_name='Sabor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Salgado',
                'verbose_name_plural': 'Salgados',
            },
            bases=('taberna.produto',),
        ),
        migrations.RenameField(
            model_name='precopizza',
            old_name='criado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='precopizza',
            old_name='modificado',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='precopizza',
            old_name='preco_m',
            new_name='price_a',
        ),
        migrations.RenameField(
            model_name='precopizza',
            old_name='preco_g',
            new_name='price_b',
        ),
        migrations.RenameField(
            model_name='precopizza',
            old_name='preco_f',
            new_name='price_f',
        ),
        migrations.RenameField(
            model_name='precopizza',
            old_name='preco_p',
            new_name='price_s',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='criado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='imagem',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='modificado',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='produto',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='precopizza',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AddField(
            model_name='precopizza',
            name='price_m',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=8, verbose_name='Preço Mini'),
        ),
        migrations.AddField(
            model_name='produto',
            name='stock',
            field=models.BooleanField(default=True, verbose_name='Estoque'),
        ),
    ]
