# Generated by Django 3.0.6 on 2020-07-14 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refrigerante',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taberna.Produto')),
                ('p1l', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='1 Litro')),
                ('p2l', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='2 Litros')),
                ('ppequeno', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Pequeno')),
            ],
            options={
                'verbose_name': 'Refrigerante',
                'verbose_name_plural': 'Refrigerantes',
            },
            bases=('taberna.produto',),
        ),
    ]
