# Generated by Django 3.0.6 on 2020-11-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0002_auto_20201110_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.CharField(max_length=50, verbose_name='Data'),
        ),
    ]
