# Generated by Django 3.0.6 on 2020-07-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0002_refrigerante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refrigerante',
            name='p1l',
        ),
        migrations.RemoveField(
            model_name='refrigerante',
            name='p2l',
        ),
        migrations.RemoveField(
            model_name='refrigerante',
            name='ppequeno',
        ),
    ]
