# Generated by Django 3.0.6 on 2020-11-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0003_auto_20201110_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date',
        ),
    ]
