# Generated by Django 3.0.6 on 2020-11-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0004_remove_cart_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='User')),
                ('date', models.CharField(max_length=20, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Datas',
            },
        ),
    ]
