# Generated by Django 3.0.6 on 2020-07-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0005_auto_20200715_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='refrigerante',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Preço'),
            preserve_default=False,
        ),
    ]
