# Generated by Django 3.0.6 on 2020-07-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0006_refrigerante_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precopizza',
            name='preco_m',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=8, verbose_name='Preço Mini'),
        ),
    ]
