# Generated by Django 3.0.6 on 2020-08-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0007_auto_20200725_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='precopizza',
            name='preco_a',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=8, verbose_name='Preço Média'),
        ),
    ]
