# Generated by Django 3.0.6 on 2020-09-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0009_drink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='liters',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Litros/Ml'),
        ),
    ]
