# Generated by Django 3.0.6 on 2020-09-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0010_auto_20200908_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='liters',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Litros/Ml'),
        ),
    ]
