# Generated by Django 3.0.6 on 2020-09-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0011_auto_20200908_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='brand',
            field=models.CharField(default=1, max_length=40, verbose_name='Marca'),
            preserve_default=False,
        ),
    ]
