# Generated by Django 3.0.6 on 2020-09-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0012_drink_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='brand',
        ),
    ]
