# Generated by Django 3.0.6 on 2020-09-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0013_remove_drink_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taberna.Produto')),
                ('flavor', models.CharField(max_length=100, verbose_name='Sabor')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Salgado',
                'verbose_name_plural': 'Salgados',
            },
            bases=('taberna.produto',),
        ),
        migrations.RemoveField(
            model_name='precopizza',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.AddField(
            model_name='produto',
            name='stock',
            field=models.BooleanField(default=True, verbose_name='Estoque'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('beer', 'Cerveja'), ('whisky', 'Whisky'), ('vodka', 'Vodka'), ('energetic', 'Energético'), ('cognac', 'Conhaque'), ('cachaça', 'Cachaça'), ('rum', 'Rum'), ('soda', 'Refrigerante'), ('varied', 'Variados')], max_length=10, verbose_name='Categoria'),
        ),
    ]
