# Generated by Django 3.0.6 on 2020-10-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0015_auto_20200917_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('beer', 'Cerveja'), ('whisky', 'Whisky'), ('vodka', 'Vodka'), ('energetic', 'Energético'), ('cognac', 'Conhaque'), ('cachaça', 'Cachaça'), ('rum', 'Rum'), ('soda', 'Refrigerante'), ('wine', 'Vinho'), ('varied', 'Variados')], max_length=10, verbose_name='Categoria'),
        ),
    ]
