# Generated by Django 3.0.6 on 2020-10-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0016_auto_20201014_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Refrigerante',
        ),
    ]
