# Generated by Django 3.0.6 on 2020-10-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taberna', '0017_delete_refrigerante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modificado')),
                ('user', models.CharField(max_length=255, verbose_name='User')),
                ('product', models.CharField(max_length=255, verbose_name='Produto')),
                ('product_id', models.PositiveIntegerField(verbose_name='Produto ID')),
                ('price', models.FloatField(verbose_name='Preço')),
                ('amount', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('image', models.CharField(max_length=2000, verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
